### ISSUE TITLE
"Run your network" crashes

### ISSUE THREAD

**Issue by peterkunnas** [mpicbg-csbd/CSBDeep#7]
Hi and thank you for the awesome code for image restoration. 

I was able to train my model succesfully in Collaboratory and saved it on my disc. However, when I select "Run your net work" from the menu I get following error message:
"The module "mpicbg.csbd.commands.GenericNetwork" failed to initialize."

 I would be grateful for any ideas how to solve this.
Thanks, Peter

Console gives me a following information:

[INFO] imagej-tensorflow version: 1.0.1
[INFO] tensorflow version: 1.6.0
[INFO] The current library path is: LD_LIBRARY_PATH=null
[INFO] Couldn't load tensorflow GPU support.
[INFO] If the problem is CUDA related, make sure CUDA and cuDNN are in the LD_LIBRARY_PATH.
[INFO] Using CPU version from jar file.
modelInitialized
[ERROR] null
org.scijava.module.MethodCallException: Error executing method: mpicbg.csbd.commands.GenericNetwork#modelInitialized
	at org.scijava.module.MethodRef.execute(MethodRef.java:74)
	at org.scijava.module.AbstractModuleItem.initialize(AbstractModuleItem.java:202)
	at org.scijava.module.AbstractModule.initialize(AbstractModule.java:95)
	at org.scijava.module.process.InitPreprocessor.process(InitPreprocessor.java:62)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:105)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:157)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.scijava.module.MethodRef.execute(MethodRef.java:70)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.scijava.io.http.HTTPLocation.<init>(HTTPLocation.java:101)
	at org.scijava.io.http.HTTPLocation.<init>(HTTPLocation.java:114)
	at mpicbg.csbd.util.IOHelper.loadFileOrURL(IOHelper.java:25)
	at mpicbg.csbd.network.DefaultNetwork.loadModel(DefaultNetwork.java:51)
	at mpicbg.csbd.network.task.DefaultModelLoader.loadNetwork(DefaultModelLoader.java:41)
	at mpicbg.csbd.network.task.DefaultModelLoader.run(DefaultModelLoader.java:21)
	at mpicbg.csbd.commands.CSBDeepCommand.prepareInputAndNetwork(CSBDeepCommand.java:288)
	at mpicbg.csbd.commands.GenericNetwork.prepareInputAndNetwork(GenericNetwork.java:200)
	at mpicbg.csbd.commands.GenericNetwork.modelInitialized(GenericNetwork.java:102)
	... 17 more

**Comment by fjug** [comment]
Hi @Pepperify, what happened, did it work at the end, or why did you close this issue?

**Comment by peterkunnas** [comment]
Hi fjug and thank you for the reply.

I closed the issue because I realized it I created it under the CSBDeep Website. Then I found a recent thread where it was adviced to downgrade Tensorflow to 1.3.0. Just working on it! I'll  let you know how it goes.

**Comment by peterkunnas** [comment]
Ok, I moved my discussion to an existing thread:

https://github.com/CSBDeep/CSBDeep_fiji/issues/16#issuecomment-443527236

Thanks
